BUILD_DIRECTORY=build
HELLO_OBJECT_FILE=$(BUILD_DIRECTORY)/hello.o
HELLO_BINARY_FILE=$(BUILD_DIRECTORY)/hello
PRACTICE_OBJECT_FILE=$(BUILD_DIRECTORY)/practice.o
PRACTICE_BINARY_FILE=$(BUILD_DIRECTORY)/practice

.SUFFIXES:

all: hello

$(BUILD_DIRECTORY):
	mkdir -p $(BUILD_DIRECTORY)

$(HELLO_BINARY_FILE): $(BUILD_DIRECTORY)
	nasm -f elf32 -o $(HELLO_OBJECT_FILE) hello.asm -F dwarf
	cc -m32 -o $(HELLO_BINARY_FILE) $(HELLO_OBJECT_FILE)

hello: $(HELLO_BINARY_FILE)

run-hello: $(HELLO_BINARY_FILE)
	$(HELLO_BINARY_FILE)

$(PRACTICE_BINARY_FILE): $(BUILD_DIRECTORY)
	nasm -f elf32 -o $(PRACTICE_OBJECT_FILE) practice.asm -F dwarf
	cc -m32 -o $(PRACTICE_BINARY_FILE) $(PRACTICE_OBJECT_FILE)

practice: $(PRACTICE_BINARY_FILE)

run-practice: $(PRACTICE_BINARY_FILE)
	$(PRACTICE_BINARY_FILE)

.PHONY: clean

clean:
	rm -r $(BUILD_DIRECTORY)
